// Mock ingredients data for testing navigation
export const mockIngredients = [
  // Dairy
  {
    id: "oat-milk",
    name: "Oat Milk",
    unit: "oz",
    currentStock: 120,
    minStock: 30,
    maxStock: 200,
    costPerUnit: 0.15,
    supplier: "Plant-Based Co.",
    shelfLife: 14,
    category: "dairy",
    lastRestocked: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "almond-milk",
    name: "Almond Milk",
    unit: "oz",
    currentStock: 80,
    minStock: 20,
    maxStock: 150,
    costPerUnit: 0.18,
    supplier: "Plant-Based Co.",
    shelfLife: 14,
    category: "dairy",
    lastRestocked: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "coconut-milk",
    name: "Coconut Milk",
    unit: "oz",
    currentStock: 60,
    minStock: 15,
    maxStock: 100,
    costPerUnit: 0.22,
    supplier: "Tropical Foods",
    shelfLife: 21,
    category: "dairy",
    lastRestocked: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "heavy-cream",
    name: "Heavy Cream",
    unit: "oz",
    currentStock: 40,
    minStock: 10,
    maxStock: 80,
    costPerUnit: 0.25,
    supplier: "Local Dairy",
    shelfLife: 7,
    category: "dairy",
    lastRestocked: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "half-and-half",
    name: "Half and Half",
    unit: "oz",
    currentStock: 50,
    minStock: 12,
    maxStock: 100,
    costPerUnit: 0.20,
    supplier: "Local Dairy",
    shelfLife: 7,
    category: "dairy",
    lastRestocked: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  // Coffee
  {
    id: "colombian-beans",
    name: "Colombian Coffee Beans",
    unit: "lb",
    currentStock: 15,
    minStock: 3,
    maxStock: 30,
    costPerUnit: 8.50,
    supplier: "Coffee Roasters Inc.",
    shelfLife: 30,
    category: "coffee",
    lastRestocked: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "ethiopian-beans",
    name: "Ethiopian Coffee Beans",
    unit: "lb",
    currentStock: 12,
    minStock: 2,
    maxStock: 25,
    costPerUnit: 9.25,
    supplier: "Coffee Roasters Inc.",
    shelfLife: 30,
    category: "coffee",
    lastRestocked: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "decaf-beans",
    name: "Decaf Coffee Beans",
    unit: "lb",
    currentStock: 8,
    minStock: 2,
    maxStock: 20,
    costPerUnit: 7.75,
    supplier: "Coffee Roasters Inc.",
    shelfLife: 30,
    category: "coffee",
    lastRestocked: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "guatemalan-beans",
    name: "Guatemalan Coffee Beans",
    unit: "lb",
    currentStock: 10,
    minStock: 2,
    maxStock: 20,
    costPerUnit: 8.75,
    supplier: "Coffee Roasters Inc.",
    shelfLife: 30,
    category: "coffee",
    lastRestocked: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "sumatra-beans",
    name: "Sumatra Coffee Beans",
    unit: "lb",
    currentStock: 7,
    minStock: 1,
    maxStock: 15,
    costPerUnit: 9.50,
    supplier: "Coffee Roasters Inc.",
    shelfLife: 30,
    category: "coffee",
    lastRestocked: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  // Sweeteners
  {
    id: "vanilla-syrup",
    name: "Vanilla Syrup",
    unit: "oz",
    currentStock: 45,
    minStock: 10,
    maxStock: 80,
    costPerUnit: 0.35,
    supplier: "Flavor Masters",
    shelfLife: 90,
    category: "sweetener",
    lastRestocked: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "caramel-syrup",
    name: "Caramel Syrup",
    unit: "oz",
    currentStock: 35,
    minStock: 8,
    maxStock: 70,
    costPerUnit: 0.40,
    supplier: "Flavor Masters",
    shelfLife: 90,
    category: "sweetener",
    lastRestocked: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "hazelnut-syrup",
    name: "Hazelnut Syrup",
    unit: "oz",
    currentStock: 25,
    minStock: 5,
    maxStock: 50,
    costPerUnit: 0.42,
    supplier: "Flavor Masters",
    shelfLife: 90,
    category: "sweetener",
    lastRestocked: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "cinnamon-syrup",
    name: "Cinnamon Syrup",
    unit: "oz",
    currentStock: 20,
    minStock: 5,
    maxStock: 40,
    costPerUnit: 0.38,
    supplier: "Flavor Masters",
    shelfLife: 90,
    category: "sweetener",
    lastRestocked: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "pumpkin-spice-syrup",
    name: "Pumpkin Spice Syrup",
    unit: "oz",
    currentStock: 15,
    minStock: 3,
    maxStock: 30,
    costPerUnit: 0.45,
    supplier: "Flavor Masters",
    shelfLife: 90,
    category: "sweetener",
    lastRestocked: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "brown-sugar",
    name: "Brown Sugar",
    unit: "lb",
    currentStock: 8,
    minStock: 2,
    maxStock: 15,
    costPerUnit: 1.25,
    supplier: "Bulk Foods Ltd.",
    shelfLife: 365,
    category: "sweetener",
    lastRestocked: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "honey",
    name: "Honey",
    unit: "oz",
    currentStock: 30,
    minStock: 8,
    maxStock: 60,
    costPerUnit: 0.50,
    supplier: "Local Apiary",
    shelfLife: 365,
    category: "sweetener",
    lastRestocked: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "agave-syrup",
    name: "Agave Syrup",
    unit: "oz",
    currentStock: 18,
    minStock: 5,
    maxStock: 35,
    costPerUnit: 0.55,
    supplier: "Natural Sweeteners Co.",
    shelfLife: 180,
    category: "sweetener",
    lastRestocked: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  // Pastries
  {
    id: "croissants",
    name: "Croissants",
    unit: "pcs",
    currentStock: 24,
    minStock: 6,
    maxStock: 48,
    costPerUnit: 1.25,
    supplier: "Local Bakery",
    shelfLife: 2,
    category: "pastry",
    lastRestocked: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "muffins",
    name: "Muffins",
    unit: "pcs",
    currentStock: 18,
    minStock: 4,
    maxStock: 36,
    costPerUnit: 1.50,
    supplier: "Local Bakery",
    shelfLife: 3,
    category: "pastry",
    lastRestocked: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "scones",
    name: "Scones",
    unit: "pcs",
    currentStock: 12,
    minStock: 3,
    maxStock: 24,
    costPerUnit: 1.75,
    supplier: "Local Bakery",
    shelfLife: 2,
    category: "pastry",
    lastRestocked: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "bagels",
    name: "Bagels",
    unit: "pcs",
    currentStock: 20,
    minStock: 5,
    maxStock: 40,
    costPerUnit: 1.00,
    supplier: "Local Bakery",
    shelfLife: 2,
    category: "pastry",
    lastRestocked: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "cookies",
    name: "Cookies",
    unit: "pcs",
    currentStock: 36,
    minStock: 8,
    maxStock: 72,
    costPerUnit: 0.75,
    supplier: "Local Bakery",
    shelfLife: 5,
    category: "pastry",
    lastRestocked: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "cinnamon-rolls",
    name: "Cinnamon Rolls",
    unit: "pcs",
    currentStock: 16,
    minStock: 4,
    maxStock: 32,
    costPerUnit: 2.25,
    supplier: "Local Bakery",
    shelfLife: 2,
    category: "pastry",
    lastRestocked: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  // Other ingredients
  {
    id: "chocolate-chips",
    name: "Chocolate Chips",
    unit: "lb",
    currentStock: 5,
    minStock: 1,
    maxStock: 10,
    costPerUnit: 4.50,
    supplier: "Baking Supplies Co.",
    shelfLife: 180,
    category: "other",
    lastRestocked: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "cocoa-powder",
    name: "Cocoa Powder",
    unit: "lb",
    currentStock: 3,
    minStock: 0.5,
    maxStock: 6,
    costPerUnit: 6.25,
    supplier: "Baking Supplies Co.",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "vanilla-extract",
    name: "Vanilla Extract",
    unit: "oz",
    currentStock: 8,
    minStock: 2,
    maxStock: 16,
    costPerUnit: 2.75,
    supplier: "Baking Supplies Co.",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "baking-soda",
    name: "Baking Soda",
    unit: "lb",
    currentStock: 2,
    minStock: 0.5,
    maxStock: 4,
    costPerUnit: 1.50,
    supplier: "Baking Supplies Co.",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "baking-powder",
    name: "Baking Powder",
    unit: "lb",
    currentStock: 1.5,
    minStock: 0.25,
    maxStock: 3,
    costPerUnit: 2.25,
    supplier: "Baking Supplies Co.",
    shelfLife: 180,
    category: "other",
    lastRestocked: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "flour",
    name: "All-Purpose Flour",
    unit: "lb",
    currentStock: 25,
    minStock: 5,
    maxStock: 50,
    costPerUnit: 0.75,
    supplier: "Bulk Foods Ltd.",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "eggs",
    name: "Large Eggs",
    unit: "pcs",
    currentStock: 60,
    minStock: 12,
    maxStock: 120,
    costPerUnit: 0.25,
    supplier: "Local Farm",
    shelfLife: 14,
    category: "other",
    lastRestocked: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "butter",
    name: "Unsalted Butter",
    unit: "lb",
    currentStock: 8,
    minStock: 2,
    maxStock: 16,
    costPerUnit: 3.50,
    supplier: "Local Dairy",
    shelfLife: 30,
    category: "other",
    lastRestocked: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "olive-oil",
    name: "Extra Virgin Olive Oil",
    unit: "oz",
    currentStock: 32,
    minStock: 8,
    maxStock: 64,
    costPerUnit: 0.40,
    supplier: "Mediterranean Imports",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "coconut-oil",
    name: "Coconut Oil",
    unit: "oz",
    currentStock: 16,
    minStock: 4,
    maxStock: 32,
    costPerUnit: 0.60,
    supplier: "Tropical Foods",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "sea-salt",
    name: "Sea Salt",
    unit: "lb",
    currentStock: 2,
    minStock: 0.5,
    maxStock: 4,
    costPerUnit: 2.50,
    supplier: "Bulk Foods Ltd.",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "black-pepper",
    name: "Black Pepper",
    unit: "oz",
    currentStock: 4,
    minStock: 1,
    maxStock: 8,
    costPerUnit: 1.25,
    supplier: "Spice World",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "cinnamon",
    name: "Ground Cinnamon",
    unit: "oz",
    currentStock: 6,
    minStock: 1.5,
    maxStock: 12,
    costPerUnit: 0.85,
    supplier: "Spice World",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "nutmeg",
    name: "Ground Nutmeg",
    unit: "oz",
    currentStock: 2,
    minStock: 0.5,
    maxStock: 4,
    costPerUnit: 1.50,
    supplier: "Spice World",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "cardamom",
    name: "Ground Cardamom",
    unit: "oz",
    currentStock: 1,
    minStock: 0.25,
    maxStock: 2,
    costPerUnit: 3.25,
    supplier: "Spice World",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "ginger",
    name: "Ground Ginger",
    unit: "oz",
    currentStock: 3,
    minStock: 0.75,
    maxStock: 6,
    costPerUnit: 1.75,
    supplier: "Spice World",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "cloves",
    name: "Ground Cloves",
    unit: "oz",
    currentStock: 1.5,
    minStock: 0.25,
    maxStock: 3,
    costPerUnit: 2.75,
    supplier: "Spice World",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "allspice",
    name: "Ground Allspice",
    unit: "oz",
    currentStock: 1,
    minStock: 0.25,
    maxStock: 2,
    costPerUnit: 2.25,
    supplier: "Spice World",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "star-anise",
    name: "Star Anise",
    unit: "oz",
    currentStock: 0.5,
    minStock: 0.1,
    maxStock: 1,
    costPerUnit: 4.50,
    supplier: "Spice World",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000),
    isActive: true,
    },
  {
    id: "lavender",
    name: "Dried Lavender",
    unit: "oz",
    currentStock: 0.25,
    minStock: 0.05,
    maxStock: 0.5,
    costPerUnit: 8.75,
    supplier: "Herb Garden Co.",
    shelfLife: 180,
    category: "other",
    lastRestocked: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "rose-petals",
    name: "Dried Rose Petals",
    unit: "oz",
    currentStock: 0.15,
    minStock: 0.03,
    maxStock: 0.3,
    costPerUnit: 12.50,
    supplier: "Herb Garden Co.",
    shelfLife: 180,
    category: "other",
    lastRestocked: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "chamomile",
    name: "Dried Chamomile",
    unit: "oz",
    currentStock: 0.5,
    minStock: 0.1,
    maxStock: 1,
    costPerUnit: 6.25,
    supplier: "Herb Garden Co.",
    shelfLife: 180,
    category: "other",
    lastRestocked: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "mint-leaves",
    name: "Dried Mint Leaves",
    unit: "oz",
    currentStock: 0.75,
    minStock: 0.15,
    maxStock: 1.5,
    costPerUnit: 4.25,
    supplier: "Herb Garden Co.",
    shelfLife: 180,
    category: "other",
    lastRestocked: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "lemon-zest",
    name: "Dried Lemon Zest",
    unit: "oz",
    currentStock: 0.3,
    minStock: 0.06,
    maxStock: 0.6,
    costPerUnit: 7.50,
    supplier: "Herb Garden Co.",
    shelfLife: 90,
    category: "other",
    lastRestocked: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "orange-zest",
    name: "Dried Orange Zest",
    unit: "oz",
    currentStock: 0.25,
    minStock: 0.05,
    maxStock: 0.5,
    costPerUnit: 7.75,
    supplier: "Herb Garden Co.",
    shelfLife: 90,
    category: "other",
    lastRestocked: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "vanilla-beans",
    name: "Vanilla Beans",
    unit: "pcs",
    currentStock: 12,
    minStock: 2,
    maxStock: 24,
    costPerUnit: 3.50,
    supplier: "Premium Spices",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "cinnamon-sticks",
    name: "Cinnamon Sticks",
    unit: "pcs",
    currentStock: 8,
    minStock: 2,
    maxStock: 16,
    costPerUnit: 0.75,
    supplier: "Premium Spices",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "whole-cloves",
    name: "Whole Cloves",
    unit: "oz",
    currentStock: 2,
    minStock: 0.5,
    maxStock: 4,
    costPerUnit: 1.25,
    supplier: "Premium Spices",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: "cardamom-pods",
    name: "Cardamom Pods",
    unit: "oz",
    currentStock: 1.5,
    minStock: 0.3,
    maxStock: 3,
    costPerUnit: 2.50,
    supplier: "Premium Spices",
    shelfLife: 365,
    category: "other",
    lastRestocked: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000),
    isActive: true,
  }
];
